apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/maxtrautwein/paralleleverteiltesysteme-lab:master
          ports:
            - containerPort: 8080
          env:
            - name: DOTNET_ENVIRONMENT # Select "Development" for OpenAPI & Swagger Endpoints
              value: "Production"
            #- name: WEBAPI_PORT # You may change the Internal Port from the default of 8080
            #  value: "8080"
            - name: ConnectionString
              value: "Host=database;Username=postgres;Password=examplePw;Database=postgres"
            #- name: ServiceName  # Override The Service Name used for OTLP
            #  value: "Parallel-Sys-MaxTrautwein"
            #- name: OtlpToConsole # set to true to enable log to Console. Useful if you don't have an endpoint
            #  value: "false"
            #- name: OtlpEndpoint  # Where to send Telemetery Data. Nothing will be sent if unset
            #  value: "http://jaeger:4317"
